# Welcome to Numpy

In [1]:
import numpy as np


In [6]:
myarr = np.array([[3,6,32,7]], np.int32)

In [5]:
myarr

array([ 3,  6, 32,  7])

In [7]:
myarr.shape

(1, 4)

In [8]:
myarr.dtype

dtype('int32')

In [9]:
myarr[0,1]

6

In [10]:
myarr[0,1] = 45

In [11]:
myarr

array([[ 3, 45, 32,  7]])

# Array creation : Convertion from other Python structures

In [17]:
import numpy as np

In [18]:
listArray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [13]:
listArray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
listArray.shape

(3, 3)

In [15]:
listArray.size

9

In [16]:
np.array({34,23,45})

array({34, 45, 23}, dtype=object)

In [19]:
zeros = np.zeros((3,3))

In [20]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [21]:
rng = np.arange(15)

In [22]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
lspace = np.linspace(1,50,23)

In [24]:
lspace

array([ 1.        ,  3.22727273,  5.45454545,  7.68181818,  9.90909091,
       12.13636364, 14.36363636, 16.59090909, 18.81818182, 21.04545455,
       23.27272727, 25.5       , 27.72727273, 29.95454545, 32.18181818,
       34.40909091, 36.63636364, 38.86363636, 41.09090909, 43.31818182,
       45.54545455, 47.77272727, 50.        ])

In [19]:
emp = np.empty((3,3))

In [27]:
emp

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [29]:
arr = np.arange(40)

In [30]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [31]:
arr.reshape(2,20)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
        36, 37, 38, 39]])

In [32]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [33]:
arr.shape

(40,)

In [22]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [23]:
ar = np.array(x)

In [24]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [25]:
ar.sum(axis=0)

array([12, 15, 18])

In [26]:
ar.sum(axis=1)

array([ 6, 15, 24])

In [27]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [28]:
ar.flat

In [31]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [32]:
ar.ndim

2

In [33]:
ar.size

9

In [34]:
ar.shape

(3, 3)

In [35]:
ar.nbytes

36

In [36]:
one = np.array([1,3,5,24,990])

In [37]:
one.argmax()

4

In [38]:
one.argmin()

0

In [39]:
one.argsort()

array([0, 1, 2, 3, 4], dtype=int64)

In [40]:
one.sort()

In [41]:
one

array([  1,   3,   5,  24, 990])

In [42]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
ar.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
np.where(ar>4)

(array([1, 1, 2, 2, 2], dtype=int64), array([1, 2, 0, 1, 2], dtype=int64))

In [47]:
type(np.where(ar>4))

tuple